server:
  port: 8081

spring:
  application:
    name: provider-service
  datasource:
    url: jdbc:postgresql://localhost:5433/pawsnearme?currentSchema=providers,identity,public&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: providers
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  server:
    port: 9091

