server:
  port: 8082

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5433/pawsnearme?currentSchema=catalog,providers,identity,public&stringtype=unspecified
    username: catalog_service_role
    password: catalog_service_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: catalog
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
